const GET_BONDS = "GET_BONDS";
const GET_INVESTORS = "GET_INVESTORS";
const GET_QUERY  = "GET_QUERY ";
 
const GET_SINGLE_INVESTOR = "GET_SINGLE_INVESTOR";
const GET_INVESTOR_PORTFOLIO = "GET_INVESTOR_PORTFOLIO";
const GET_AMOUNT_INVESTED = "GET_AMOUNT_INVESTED";
const ADD_INVESTMENT = "ADD_INVESTMENT";
const CANCEL_INVESTMENT = "CANCEL_INVESTMENT";

 

export { GET_BONDS , GET_INVESTORS , GET_QUERY  , GET_SINGLE_INVESTOR, GET_AMOUNT_INVESTED, ADD_INVESTMENT, CANCEL_INVESTMENT , GET_INVESTOR_PORTFOLIO};
